version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-rate-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/currency_rate
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: currency-rate-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_rate
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
